server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      file-size-threshold: 20KB
  application:    name: zuul-server
eureka:
  client:
   serviceUrl:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    security:      serviceId: security-service